version: '2'

services:
  verdaccio:
    image: verdaccio/verdaccio:4.0.0-alpha.4
    container_name: verdaccio-server
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
      - './plugins:/verdaccio/plugins'
